package com.ragego.gui.objects;

import com.badlogic.gdx.maps.tiled.TiledMapTile;
import com.ragego.engine.Intersection;
import com.ragego.engine.Stone;

/**
 * Represents a {@link Stone} on the Goban.
 */
public class GraphicStone {

    /**
     * Stone loaded from the {@link com.ragego.engine.GameBoard}
     */
    private final Stone stone;

    /**
     * Graphic goban where this stone is.
     */
    private final Goban goban;

    /**
     * The tiles which represents this stone.
     */
    private final TiledMapTile stoneTile;

    /**
     * Create a new GraphicalStone to be placed on the board
     * @param stone The stone given by {@link com.ragego.engine.GameBoard}
     * @param goban The goban where we are playing.
     */
    public GraphicStone(Stone stone, Goban goban) {
        this.stone = stone;
        this.goban = goban;
        this.stoneTile = generateTile();
    }

    /**
     * Generate the tiles for the given stone.
     * @return The tile which can be shown for this stone.
     */
    private TiledMapTile generateTile() {
        if ((stone != null && stone.getPlayer() != null) && (goban != null && goban.getBoard() != null)) {
            if (goban.getBoard().getLetterForPlayer(stone.getPlayer()) == 'B') {
                return goban.getBlackStoneTile();
            } else return goban.getWhiteStoneTile();
        } else {
            return null;
        }
    }

    /**
     * Intersection where this stone lives.
     * @return The intersection
     */
    public Intersection getIntersection() {
        return stone.getPosition();
    }

    /**
     * Stone tile for this graphic stone
     * @return The tile generated by the constructor
     */
    public TiledMapTile getStoneTile() {
        return stoneTile;
    }

    /**
     * Accessor for the original stone
     * @return Access to the stone from the engine.
     */
    public Stone getStone() {
        return stone;
    }
}
